name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Compile LaTeX with a custom output filename
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -jobname=agao25_script

      # Step 3: Upload the generated PDF as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: agao25_script
          path: agao25_script.pdf

      # Step 4: Commit and push the PDF to the main branch
      - name: Commit and push PDF to main
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add and commit the PDF
          git add agao25_script.pdf || echo "No changes to commit"
          git commit -m "Update PDF [skip ci]" || echo "No changes to commit"

          # Push to main (force-push to overwrite history if needed)
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
